# Generated by Django 4.0.4 on 2022-06-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_packages_remove_customerorder_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='description',
            new_name='moviedescription',
        ),
        migrations.RenameField(
            model_name='packages',
            old_name='packagename',
            new_name='moviename',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='price',
        ),
        migrations.AddField(
            model_name='packages',
            name='settime',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='ticketprice',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
