# Generated by Django 4.0.4 on 2022-06-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_description_packages_moviedescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='service',
            new_name='moviename',
        ),
        migrations.AlterField(
            model_name='packages',
            name='moviedescription',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
