# Generated by Django 4.0.4 on 2022-06-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_service_appointment_moviename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='noofticket',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
