# Generated by Django 4.0.4 on 2022-06-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_settime_packages_endtime_packages_starttime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='endtime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='packages',
            old_name='starttime',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='packages',
            name='showdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
