# Generated by Django 4.0.4 on 2022-06-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_endtime_packages_end_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Packages',
        ),
    ]
