# Generated by Django 4.0.4 on 2022-06-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='movie_info',
        ),
        migrations.AlterField(
            model_name='seat',
            name='totalseat',
            field=models.PositiveIntegerField(blank=b'I01\n', null=b'I01\n'),
        ),
    ]
