# Generated by Django 4.0.4 on 2022-06-22 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_alter_seat_totalseat'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='customer',
            field=models.ForeignKey(blank=b'I01\n', null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='seat',
            name='movie_info',
            field=models.ForeignKey(blank=b'I01\n', null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='app.moviesinformation'),
            preserve_default=b'I01\n',
        ),
    ]
