# Generated by Django 3.0.14 on 2022-09-09 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20220817_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=b'I01\n', max_length=254, null=b'I01\n')),
                ('contact', models.CharField(max_length=100)),
                ('no_of_seats', models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n')),
                ('showdate', models.PositiveIntegerField(blank=b'I01\n', default=0, null=b'I01\n')),
                ('movie_name', models.ForeignKey(blank=b'I01\n', null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='app.MoviesInformation')),
            ],
            options={
                'verbose_name_plural': 'Seat',
            },
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
