# Generated by Django 3.0.2 on 2022-09-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20220909_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='showdate',
            new_name='show_date',
        ),
        migrations.AddField(
            model_name='seat',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='no_of_seats',
            field=models.PositiveIntegerField(blank=b'I01\n', max_length=100, null=b'I01\n'),
        ),
    ]
