# Generated by Django 3.0.2 on 2022-09-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20220909_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='show_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
