# Generated by Django 3.0.2 on 2022-09-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20220909_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesinformation',
            name='choosedate',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='price',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='show_date',
        ),
    ]
